### ISSUE TITLE
Ampersands (&) in event names throw xmlParseEntityRef: no name errors

### ISSUE THREAD

**Issue by lifeofbrian** [mendhak/waveshare-epaper-display#14]
Issue happens during "EXPORT TO PNG" phase

**Comment by lifeofbrian** [comment]
I'm going to go ahead and submit a pull request for this one. 

Example text: "Stay at Hampton Inn & Suite"

**Comment by mendhak** [comment]
Nicely spotted thanks.  Merged it.
