### ISSUE TITLE
Security: Do not require sudoers rights in order to run the script

### ISSUE THREAD

**Issue by lifeofbrian** [mendhak/waveshare-epaper-display#15]
I notice that the script has separate scripts that require sudoers rights, and as a result the environment variables are not passed along to those scripts, so for example the display.py logic to handle the v2 of the ePaper display doesn't work

**Comment by lifeofbrian** [comment]
I will submit a pull request on this one

**Comment by mendhak** [comment]
Thanks! Just testing it now

**Comment by mendhak** [comment]
Looks good, no sudo required.    
In case it doesn't work  after merging, it's probably because some files are owned by root.   
Do an `ls -lah` then make sure to `sudo chown pi:pi xxxx` any files that are owned by root.

**Comment by mendhak** [comment]
Thanks, closing issues now.

**Comment by lifeofbrian** [comment]
Great!
