### ISSUE TITLE
cairosvg: error: no such option: --output-width

### ISSUE THREAD

**Issue by DominicBoisvert** [mendhak/waveshare-epaper-display#30]
Hi,

With cairoSVG (pyhton3-cairosvg package), I got the following error message: cairosvg: error: no such option: --output-width

I changed "--output-width" to "-W" and "--output-height" to "-H" (line 26 of the run.sh file).

The error message is gone, and the display is good.

**Comment by mendhak** [comment]
Thanks for reporting that, did you install cairosvg using apt or pip?  What version appears when you run `cairosvg --version` ?

I wonder if the [arguments are newer](https://cairosvg.org/documentation/) maybe.

**Comment by mendhak** [comment]
Strangely for me when I use `-W` and `-H` the image that's generated is the wrong dimensions and doesn't display on the epaper screen (it errors with 'wrong dimensions'). 

I had to use --output-width and --output-height to get it working.

**Comment by DominicBoisvert** [comment]
Thanks for the quick return.

The package was python3-cairosvg, installed via apt (Raspbian Buster). The version was 1.0.20.

I removed the package (via apt) and installed it with pip3. Now it shows version 2.5.2, and it's working with either combination of `--output-width` and `--output-height` or `-W` and `-H`.

**Comment by DominicBoisvert** [comment]
Installing cairosvg (version 2.5.2) with pip3 solved the issue.
